#!/usr/bin/env bash

export CONTECO_LABEL="package.kafka_connect - ModEco"
export CONTECO_DESCRIPTION="Modeco kafka connect module package."

export CONTECO_TYPE="package"
export CONTECO_NAME="kafka_connect"
export CONTECO_TAG="v1.0.0"
export CONTECO_TAG_TYPE="incremental"

export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="modeco"
